### ISSUE TITLE
cliupdate exceeds memory size

### ISSUE THREAD

**Issue by lapete** [fossar/selfoss#1222]
Selfoss Version 2.18
PHP Version 7.2.33 

Every time I run cliupdate.php I do get the following error:
`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 12288 bytes)
[vendor/simplepie/simplepie/library/SimplePie/Cache/File.php:126] 
an error occured%    `
I tried to increase the limit as suggested [here](https://stackoverflow.com/questions/415801/allowed-memory-size-of-33554432-bytes-exhausted-tried-to-allocate-43148176-byte?rq=1) and [here](https://stackoverflow.com/questions/20650692/cakephp-fatal-error-allowed-memory-size-of-536870912-bytes-exhausted-tried-t), both via the `.htaccess` and the `cliupdate.php` file, which didn't work or even lead to server errors.
The update still  seems to work, I do get new articles, but I don't know if it's all of them or if some are missing.
Size of the folders in selfoss/data:

```11M     cache  
296K    favicons  
4.0K    fulltextrss  
28M     logs  
4.0K    sqlite  
0       thumbnails  
39M     total

**Comment by jtojnar** [comment]
How are you running `cliupdate.php`? For `php_value` in `.htaccess` to work you would need to enable it in [Apache config](https://www.php.net/manual/en/configuration.changes.php) and that would not even apply when running the script from command line. `ini_set` might work better but the surest is changing it in `php.ini`.

But 512 MB should be more than enough for everything except pathologically big feeds.

Since it runs out of memory when [trying to load data from cache](https://github.com/simplepie/simplepie/blob/db9fff27b6d49eed3d4047cd3211ec8dba2f5d6e/library/SimplePie/Cache/File.php#L126), I would try to delete the contents of `data/cache` directory. Weirdly, it seems to be missing from your directory listing.

If you increase the `logger_level=DEBUG` in your `config.ini`, you should see `start fetching source …` in the logs that could point you to the last source being fetched.

**Comment by lapete** [comment]
I simply run `php cliupdate.php`.
Deleting the cache worked, thank you!
