### ISSUE TITLE
Make usage instructions clearer + demo

### ISSUE THREAD

**Issue by sheeepdev** [fossar/selfoss#1293]
Hello! I just saw selfoss while searching for a self-hosted RSS reader. From the screenshots I love the user interface, but unlike other RSS readers like [FreshRSS](https://freshrss.org) selfoss does not have a demo. It also doesn't have clear usage/installation instructions. From what I read I have no idea how to start it up. I see that there was some effort put in to try and make a docker image and it seems someone did succeed in making it. But to a normal user trying to use this it is very confusing

**Comment by jtojnar** [comment]
We have a demo here https://selfoss-test.herokuapp.com/ (username and password are `demo`), I have just updated it to latest build. Still need to set up CI to update it periodically. I have not linked it much because I worry about abuse (e.g. people adding spam feeds). Maybe I should make it read only. Or add a one-click button so that people can deploy it somewhere.

The installation instructions are on [the website](https://selfoss.aditu.de/#installation) but I can see some parts where they could be clearer (e.g. it mentions uploading files but not where one should upload them). I also tried to add some more options on the [upcoming website page](https://github.com/fossar/selfoss/blob/master/docs/content/docs/administration/installation.md) but the Docker support is still unofficial. But the installation should really be as simple as extracting selfoss into the web server directory.

**Comment by sheeepdev** [comment]
> We have a demo here [selfoss-test.herokuapp.com](https://selfoss-test.herokuapp.com/) (username and password are `demo`), I have just updated it to latest build. Still need to set up CI to update it periodically. I have not linked it much because I worry about abuse (e.g. people adding spam feeds). Maybe I should make it read only. Or add a one-click button so that people can deploy it somewhere.
> 
> The installation instructions are on [the website](https://selfoss.aditu.de/#installation) but I can see some parts where they could be clearer (e.g. it mentions uploading files but not where one should upload them). I also tried to add some more options on the [upcoming website page](https://github.com/fossar/selfoss/blob/master/docs/content/docs/administration/installation.md?rgh-link-date=2021-12-16T15%3A54%3A18Z) but the Docker support is still unofficial. But the installation should really be as simple as extracting `selfoss.zip` into the web server directory.

Nice! I would suggest you to add the demo link to the README and the website.

**Comment by jtojnar** [comment]
The Heroku unfortunately removes the free tier so we will need to find out something else.

**Comment by sheeepdev** [comment]
I suggest using maybe netlify instead?

**Comment by jtojnar** [comment]
That would work for the front-end but it does not look like Netlify supports PHP https://answers.netlify.com/t/how-to-host-php-websites/7410

**Comment by jtojnar** [comment]
I have updated the installation instructions: https://selfoss.aditu.de/docs/administration/installation/basic/
