### ISSUE TITLE
A couple minor things

### ISSUE THREAD

**Issue by deathbybandaid** [fossar/selfoss#1305]
# Version Number missing

In 2.18

![image](https://user-images.githubusercontent.com/18010545/148593520-c0fa5851-be4f-4f74-a79a-e607c1f0ee3b.png)

In 2.19

![image](https://user-images.githubusercontent.com/18010545/148593545-db596dae-153d-4d05-89ae-a5ff0f6158c3.png)

# Button sizes

As per the above images, both scaled the same, 2.19 buttons seem large

# Scroll Bar in 2.18 is nicer looking

In 2.18

![image](https://user-images.githubusercontent.com/18010545/148593784-f41690e5-8085-4126-b22f-526d5023d2fc.png)

In 2.19

![image](https://user-images.githubusercontent.com/18010545/148593846-626fdb0f-5e41-4d05-a01c-d815f9bed360.png)

**Comment by jtojnar** [comment]
- Version number missing: [intentional](https://github.com/fossar/selfoss/pull/1134#discussion_r326920499), https://github.com/fossar/selfoss/commit/f78d9fda05a1b42dc6b40a70f155e0e3c617b123 I still want to show the version somewhere but have not found the correct place yet
- Button sizes: https://github.com/fossar/selfoss/commit/1ec661875e4c68878a3ff8e461de066e684aa142, `45px` is `2.8125em` so I guess I just rounded it up. Perhaps `2.5em` would look better
- Scrollbar: we [no longer use custom scrollbar library](https://github.com/fossar/selfoss/commit/e68340df6788e7865c77a4ed6792f839eb16d023) because I could not find one that would not be buggy and ~~most browsers~~ [apparently](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars#scrollbar-width) only Firefox support thin scrollbars – this is how it looks in Firefox on GNOME:
    ![scrollbars](https://user-images.githubusercontent.com/705123/148606824-5b404dde-3d24-4591-9ae9-fce5ee21e824.png)

**Comment by deathbybandaid** [comment]
the thin scrollbar in 2.18 works in chromium-based browsers from what I've seen

**Comment by jtojnar** [comment]
Yeah, in 2.18 we used a [custom JavaScript library](http://manos.malihu.gr/jquery-custom-content-scroller/) which worked in most browsers but sometimes it bugged out. And also it was based on jQuery, which we are trying to get rid of.

Tried `2.5em` for toolbar button height but it looks too thin with large button:

![log in button @ 2.5em](https://user-images.githubusercontent.com/705123/148608152-37948721-e1b1-462b-a022-ff425862bf31.png)

but `2.8em` looks okay

![log in button @ 2.5em](https://user-images.githubusercontent.com/705123/148608725-5cbc7f3e-dd17-40cb-a094-63d5cba815ac.png)

will change it to that.

**Comment by jtojnar** [comment]
I switched it to a [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) based approach, which looks slightly less ugly (thought not as nice as 2.18).

**Comment by deathbybandaid** [comment]
looks like the checks errored at linting

**Comment by jtojnar** [comment]
Oops, I realized that a second after I pushed it and then forgot to push the fix.

**Comment by deathbybandaid** [comment]
/me applauses

absolutely beautiful!

![image](https://user-images.githubusercontent.com/18010545/148621935-9b171fcc-8349-4e9d-a77d-c89f9c833e20.png)

**Comment by deathbybandaid** [comment]
Only thing I'm struggling with is CSS tweaking so the bar isn't green on my plex theme.

In theory, it should just be:

````
.nav-ts-wrapper {

    &::-webkit-scrollbar-thumb {
        background: var(--button-color);
    }

    &::-webkit-scrollbar-thumb:hover {
        background: var(--button-color);
    }

    &::-webkit-scrollbar-thumb:active {
        background: var(--button-color-hover);
    }
}
````

**Comment by jtojnar** [comment]
The `&` is [sass](https://sass-lang.com/documentation/syntax) syntax for copying the parent selector. In plain CSS, you will need to use:

```
.nav-ts-wrapper::-webkit-scrollbar-thumb {
    background: var(--button-color);
}

.nav-ts-wrapper::-webkit-scrollbar-thumb:hover {
    background: var(--button-color);
}

.nav-ts-wrapper::-webkit-scrollbar-thumb:active {
    background: var(--button-color-hover);
}
```

**Comment by deathbybandaid** [comment]
thanks, that works, I was probably just to tired staring at it yesterday!
