### ISSUE TITLE
Release 2.19?

### ISSUE THREAD

**Issue by bertptrs** [fossar/selfoss#1351]
v2.18 is not compatible with the latest releases of many distros (Debian, Ubuntu) as they come with PHP 8.1 and therefore will result in the following error:

> PHP message: PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value

Judging by some previous issues (#1333, #1330, #1294) this and other issues have been fixed already, but they simply have not landed in a release.

Would you be willing to cut a new release from the current state of affairs?

**Comment by jtojnar** [comment]
I wanted to finish Docker image before the next release (see https://github.com/fossar/selfoss/milestone/3) but at this rate, it does not look like I will ever find time to do that so it probably does not make sense to wait for that.

I will try to push 2.19 this or the next week. If you just want to use selfoss, I would recommend the [development snapshot](https://github.com/fossar/selfoss#download) for now – they are as stable as it gets.

@radek-sprta since the [image we linked to previously](https://github.com/hardware/selfoss) is archived, would you mind if I point people to your [Docker Image](https://gitlab.com/radek-sprta/docker-selfoss) in the official documentation?

@aminecmi What is the current status of ReaderForSelfoss? Do you know if it is compatible with the latest selfoss? I did not notice any glaring issues other than broken repo links in the app and on F-Droid when I tried it now – but I do not really use a phone very much. It does not look like the issues from the old repo were transferred?

Should we still link to https://f-droid.org/packages/apps.amine.bou.readerforselfoss/, or wait for https://gitea.amine-louveau.fr/Louvorg/ReaderForSelfoss-multiplatform/issues/34?

**Comment by aminecmi** [comment]
Hi,

> Do you know if it is compatible with the latest selfoss?

I have a pretty recent version installed, and I didn’t notice any issues for now.

> It does not look like the issues from the old repo were transferred?

They open ones were. The closed ones weren’t really useful.

> I did not notice any glaring issues other than broken repo links in the app and on F-Droid when I tried it now

The next version of the app is ready to be deployed to f-droid. I’ll do that in the following days. 
The old link won’t work anymore; the new one should be https://f-droid.org/packages/bou.amine.apps.readerforselfossv2.android
Do you want to wait for the url to be up to change it ?

**Comment by jtojnar** [comment]
> The old link won’t work anymore; the new one should be https://f-droid.org/packages/bou.amine.apps.readerforselfossv2.android
> Do you want to wait for the url to be up to change it ?

Thanks for the info. I remember F-Droid updates not being the fastest so I would like to wait so that I can include a working link in the change log.

**Comment by aminecmi** [comment]
No problem at all. I’ll update you when it’s done and available.

**Comment by radek-sprta** [comment]
> @radek-sprta since the [image we linked to previously](https://github.com/hardware/selfoss) is archived, would you mind if I point people to your [Docker Image](https://gitlab.com/radek-sprta/docker-selfoss) in the official documentation?

No, I don't mind at all. Judging by the milestones, it looks like the current devel snapshot is pretty close to what 2.19 is going to be. So, I'll make sure everything works with the latest version.

**Comment by aminecmi** [comment]
@jtojnar the app is available [here](https://f-droid.org/en/packages/bou.amine.apps.readerforselfossv2.android/)

**Comment by jtojnar** [comment]
I have been doing some further testing for the release but the service worker for offline mode is just too buggy and displays annoying update warnings all the time. And if I try to start it only after user enables the offline mode, the mode gets broken completely.

So if we want to have a release soon, I need to remove the offline mode code. Anyone using it?

**Comment by jtojnar** [comment]
Turned the docs into a releasable shape. Now we just need to finish the Docker container update: https://gitlab.com/radek-sprta/docker-selfoss/-/merge_requests/1

**Comment by desbest** [comment]
> So if we want to have a release soon, I need to remove the offline mode code. Anyone using it?

The offline mode is completely unusable. I tried it for 30 seconds and it was plagued with severe bugs and basic functionality not loading or working, for me to even do anything. I used it for 30 seconds and never again.

**Comment by radek-sprta** [comment]
I just wanna thank you for the new version. Not only are there nice new features, it is really snappy as well.

**Comment by davidoskky** [comment]
Wow, this was exciting!
Frankly I didn't believe this day would have come.
Thank you @jtojnar for your great work!

**Comment by jtojnar** [comment]
Thank you all for helping with the code and reporting issue :tada:

**Comment by bertptrs** [comment]
Thank _you_ for putting together the new release. I haven't watched the development closely but it all works again, and I appreciate the new look and feel of the app. Updating was also very easy.
