### ISSUE TITLE
Reloading shows already read new

### ISSUE THREAD

**Issue by pvillaverde** [fossar/selfoss#1353]
Hey there! I recently updated from the 2.18 stable version to one of the last developments builds and I'm experiencing an unwanted beheaviour when pressing the releoad button (r).

For example I have 60 items... I started reading them and mark them as readed and at some point I reload the page. Instead of showing me the unread reamining lists, with all the items collapsed, as it did until now on 2.18, I get one of the readed news opened and all other unread collapsed. I think it has something to do with it beeing keep in the URI path (i.e. /unread/all/114994) and it's a bit annoying. I have to do a reload of the whole page or changing to new items and then back to unread to remove it from the list.

Any idea how can I fix this behaviour?

**Comment by jtojnar** [comment]
Right, clicking an article title with a mouse opens it so when you reload the page, you are also reloading opened the article.

Previously navigating with keyboard also changed the opened article in the URL but it appears it got broken (possibly by https://github.com/fossar/selfoss/commit/823e4d57447eb2b9a0427d44626865d5f99f3ee7). I am still not sure what the best interaction around this should be – either we should fix it so that the last viewed article ends up in the URI, or at least clean the initial article from URI once we start interacting with a different article (even with keyboard).

Having the `r` key clear the article id from URI also might make sense, as that is what clicking the filters in the sidebar does (since 3e1104d1dbaa6aa31ae88b9f991e84228a1a5e64). Will think it over.
