### ISSUE TITLE
Setting for enabling the columns back for reading articles

### ISSUE THREAD

**Issue by desbest** [fossar/selfoss#1372]
I was looking at the changelog (or release notes) for version 2.19 and I saw this.

> Long articles will no longer be arranged into columns, allowing for smoother reading experience (https://github.com/fossar/selfoss/pull/1081)

But I like the columns.
Can you add a new setting in `config.ini` that allows me to add the columns back?
That way people can choose whether to have it turned on or not.

**Comment by desbest** [comment]
Sorry for not wording it better. My laptop was slow due to hardware compatibility scans and Windows Update, so I couldn't post any screenshots earlier. I mean something like this.

I like having the columns because I have an autism induced visual processing disorder that is unclassifiable. I just know that I have problems with visual noise, time perception. And finally when mixing up the transversing, transforming and transmuting of the same type of attribute across multiple entities. It's long to explain.

Across various blogs and news websites, they tend to change the design of the website, as according to the reading grade, technical nature, level of field-set terminology, varying sequential nature and the varying burden of short-term and long-term memory, that is required for the reader to sufficiently understand, interpret and remember the article. For example, if I read a highly technical website like The Economist that is flooded with economics terminology, their website design will be designed in a way, to not detract from the writing style of the article at hand. Whereas a viral journalist website like Buzzfeed which is aimed at a young demographic, they're going to design their website differently than that one, in order to accomodate to the nature of the writing style.

Also can you come up with the `user.css` code that's needed to put the relevant changes back?

**Comment by jtojnar** [comment]
You can use something like the following:

```css
.entry-content.entry-content-nocolumns {
    column-count: 3;
    max-width: initial;
}
```

But I would expect having multiple columns to actually be worse for visual noise. Compare reading in forced multiple columns:

https://gfycat.com/inexperiencedwellinformedizuthrush

With the new single column:

https://gfycat.com/cheerfulillustriousblacklemur

Maybe there is a better way to adjust the style to make reading even better for users with such disorders. For example, making the single column narrower?

**Comment by jtojnar** [comment]
> It's about asking the question _"If I had never seen that website before in my life, within a space of 3 seconds, how long would it take me to figure out what the purpose of this web page and also figure out how I can go about achieving my desired daily objective? All without accidentally confusing one thing for something else._

I am not sure how does re-flowing the article text into columns help with this. The purpose of the article will typically be to convey some information, the details of which you could infer from the article title, source name and the content itself. There is no other structure as the article is purely linear.

----

I am not really sure what you mean by visual noise. I mean both of the Microsoft websites are pretty terrible, with majority of the real estate spent on ads – I would definitely call those a visual noise since they do not play any role for furthering my goals.

![Microsoft website in 2013, annotated](https://user-images.githubusercontent.com/705123/195457147-948f1004-53b9-4094-a372-e92badfeb242.png)

I would say the 2013 is better for the tasks because the menu is front and center (although I am not sure whether I should look into _Products_ or _Buy_ for a keyboard), rather than stuffed to the site. But I do not think that is related to the noise – I think 2013 page has more noise.

----

For Jumpchart, I again think both are suboptimal designs. But I still would not say there is much of a difference in their noise levels – the bigger issue is how are the features organized:

- Why is the file highlighted in a way that catches attention?
- Why is there “No files found” message?

In fact I would say the modern file list in Jumpchart is more crowded and I prefer it that way. But for working with images, the larger thumbnails would be useful so there probably should be a switch.

The paper clip and chain link icons in the text editor could look nearly identical to people with poor eyesight so that should probably be improved.

---

For WinSCP, if I disregard the toolbars overflowing with icons, which definitely succeeded in distracting me, I only see four elements in FIlezilla that are lacking from WinSCP:

- Quick connect form – but that is part of the toolbars. Never used it maybe it is useful to some people.
- FTP message log – this could probably be hidden by default. User should have most of that info from _Transfers_ pane so it should only be needed for debugging.  Though, with how reliable FTP is, I was looking at the panel all the time when I was using Filezilla, so maybe it is needed after all. **Edit:** Actually, it looks like they merged it into the _Transfers_ pane in recent versions.
- Directory trees – these are quite useful for quickly jumping through a directory tree, can be hidden if annoying.
- The green progress bars in the _Transfers_ pane – I imagine they can be distracting to some people, personally, I find them useful to quickly gauge the progress without having to focus on the number.

I am not counting the red and yellow lines since that is a comparison mode, which is not active by default.

So again I am not sure what you mean by the _visual noise_ except maybe the progress bars and message log.

**Comment by jtojnar** [comment]
Closing as it is not clear what to do here.
