### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile 

### ISSUE THREAD

**Issue by dwydler** [fossar/selfoss#1396]
Hi Guys,
i have done an upgrade from 2.18 to 2.19. I use a cron job to get new content from all my favorite websites. The cronjob use this command:
`php /home/users/idkc/www/production/selfoss/cliupdate.php > /dev/null`

Sometimes i receive an email from this cron job with follow content:
`libpng warning: iCCP: known incorrect sRGB profile`
`libpng warning: iCCP: known incorrect sRGB profile`

I do not know by which rss feed or squenze of the cliupdate.php this warning happen. Any ideas?

**Comment by jtojnar** [comment]
The issue is that libpng prints warnings to `stderr` by default:

https://github.com/glennrp/libpng/blob/5a0b7e9c29ec23f87c601622cb2db01781a6cbba/pngerror.c#L803

I do not think it is possible to silence it on selfoss side.

Ideally libgd would call `png_set_error_fn` and translate the warnings to GD specific ones, which could then be intercepted by PHP’s gd extension ~~but that probably will not happen in the near future.~~ It should have been fixed https://github.com/libgd/libgd/pull/786 but a new version is not yet available.

For now, you can redirect the `stderr` as well with `>/dev/null 2>&1`

**Comment by dwydler** [comment]
The cron job runs once a day. The strange thing is, i receive this warning not every day. It can be that i got this warnung 2 days in a row and than 5 days not. 

> For now, you can redirect the stderr as well with >/dev/null 2>&1 all other errors will be logged using the configured logging method so the silencing should not cover anything.

That would mean that i got no email anymore if any other warning or error. Right?

**Comment by jtojnar** [comment]
> The strange thing is, i receive this warning not every day. It can be that i got this warnung 2 days in a row and than 5 days not.

The warning is triggered either by resizing a site’s favicon or an article’s thumbnail. The infrequency is likely caused by the source not publishing new articles everyday.

> I get this warning since i updated to 2.19. Before it do not happen.

That might be due to a change of the algorithm that selects an appropriate icon for a source ([example](https://github.com/fossar/selfoss/commit/99d42da265d4d3fe57ffd3f9c01ae0afaa6d455f)). And the icon that is now selected as optimal has broken color profile.

> That would mean that i got no email anymore if any other warning or error. Right?

selfoss should not really print anything to stderr, unless you make it do so with `logger_destination=file:php://stderr` in `config.ini`. So you will not miss anything.

Or if you really want, you can redirect `stderr` to `stdout` and then filter with `grep`:

```bash
php cliupdate.php 2>&1 >/dev/null | grep -v "libpng warning: iCCP"
```

**Comment by dwydler** [comment]
> Or if you really want, you can redirect stderr to stdout and then filter with grep:

Thanks. If the error occur again in will try it so.
