### ISSUE TITLE
Negative keyword filtering

### ISSUE THREAD

**Issue by GutHib** [fossar/selfoss#1422]
Hi - glad to see that the app is still actively developed. It would be fantastic to get some sort of keyword filtering option, so articles/items that contain certain keywords will not be shown.

Also, it would be great to be able to delete feeds or simply clear the entire table via the app. Data can accumulate quickly, and at some point, the app simply can't handle it anymore (tiime out).

Thanks and keep up the great work!

**Comment by jtojnar** [comment]
The “Filter” field in the source supports Perl-compatible regular expressions so you could in theory express it with [negative lookaheads](https://regextutorial.org/positive-and-negative-lookahead-assertions.php). Unfortunately, for an item to be stored, the regex needs to match [either the title or the content](https://github.com/fossar/selfoss/blob/7a8c1a7adbe5a7a8a4872ee9a53e96a5663bd655/src/helpers/ContentLoader.php#L312). So in order to be filtered out, the negative lookahead would have to fail for both. There is a generic issue for the filter improvement: https://github.com/fossar/selfoss/issues/1125



> Also, it would be great to be able to delete feeds or simply clear the entire table via the app. Data can accumulate quickly, and at some point, the app simply can't handle it anymore (tiime out).

Not sure what you mean. You can already delete sources on the settings page. And item removal can be configured with `items_lifetime` option. By default, items will be cleared after 30 days of being last seen. So unless the feed is a real water hose, it should not be much of an issue.

By the way, it is better to open a single issue per feature request so it has a clear resolution criterion.

**Comment by GutHib** [comment]
Hi and thanks for the quick reply. Tbh I haven't dealt with Selfoss for a while, and Google misled me by sending me here after a "Selfoss android" search. I was actually looking to get a "delete all items" button for the Android app, but setting a reasonable lifetime on the server is probably a better solution anyway.

Thanks for pointing out the situation with the filters. Looking at the issue thread, however, it seems that I shouldn't hold my breath. You refer to the "filter field in the source" - so I guess that means this can't be used until you implement it? Again, I'm explicitly looking to filter out items, so it wouldn't help me at this point - just trying to understand what the situation is.

**Comment by jtojnar** [comment]
The issue tracker for the Android app is https://gitea.amine-louveau.fr/Louvorg/ReaderForSelfoss-multiplatform/issues

Anywho, I implemented the negative filters in #1423 and they will be available in the next version (or in the [development snapshot](https://github.com/fossar/selfoss#download)).
