### ISSUE TITLE
Filter does not seem to work

### ISSUE THREAD

**Issue by mrichtarsky** [fossar/selfoss#1426]
Hi,

for an RSS feed, I have this filter: !title:/UK/

I expect that this filters out all articles with "UK" in the title. However, article with titles as follows are still shown:

"Ofcom proposes deeper probe into UK cloud market"

Am I doing anything wrong?

Thanks and best regards,
Martin

**Comment by jtojnar** [comment]
It does appear to work for me here with `https://advanced-television.com/feed/`. Note that filters do not work retrospectively – once an item is stored in the selfoss database, it will remain there until garbage collected.

**Comment by mrichtarsky** [comment]
I creates the filter already yesterday so it should certainly be effective. But good to know the syntax is OK. I will try some other things like filtering on other fields.

**Comment by jtojnar** [comment]
You could try to apply the following changes and set `logger_level=DEBUG` in your config to get more debug info:

```patch
diff --git a/src/helpers/ContentLoader.php b/src/helpers/ContentLoader.php
index 9a5ebe86..e8c2fb03 100644
--- a/src/helpers/ContentLoader.php
+++ b/src/helpers/ContentLoader.php
@@ -31,6 +31,8 @@ class ContentLoader {
     private ThumbnailStore $thumbnailStore;
     private WebClient $webClient;
 
+    public static $log;
+
     public function __construct(Configuration $configuration, \daos\DatabaseInterface $database, IconStore $iconStore, Image $imageHelper, \daos\Items $itemsDao, Logger $logger, \daos\Sources $sourcesDao, SpoutLoader $spoutLoader, ThumbnailStore $thumbnailStore, WebClient $webClient) {
         $this->configuration = $configuration;
         $this->database = $database;
@@ -38,6 +40,7 @@ class ContentLoader {
         $this->imageHelper = $imageHelper;
         $this->itemsDao = $itemsDao;
         $this->logger = $logger;
+        self::$log = $logger;
         $this->sourcesDao = $sourcesDao;
         $this->spoutLoader = $spoutLoader;
         $this->thumbnailStore = $thumbnailStore;
diff --git a/src/helpers/Filters/MapFilter.php b/src/helpers/Filters/MapFilter.php
index e0a8125f..7c4e65fa 100644
--- a/src/helpers/Filters/MapFilter.php
+++ b/src/helpers/Filters/MapFilter.php
@@ -37,6 +37,7 @@ final class MapFilter implements Filter {
      * @param T $item
      */
     public function admits($item): bool {
+        \helpers\ContentLoader::$log->debug("trying to match with map");
         return $this->filter->admits(($this->transform)($item));
     }
 }
diff --git a/src/helpers/Filters/NegationFilter.php b/src/helpers/Filters/NegationFilter.php
index 4a22246f..56de7f6a 100644
--- a/src/helpers/Filters/NegationFilter.php
+++ b/src/helpers/Filters/NegationFilter.php
@@ -31,6 +31,7 @@ final class NegationFilter implements Filter {
      * @param T $item
      */
     public function admits($item): bool {
+        \helpers\ContentLoader::$log->debug("trying to match negation");
         return !$this->filter->admits($item);
     }
 }
diff --git a/src/helpers/Filters/RegexFilter.php b/src/helpers/Filters/RegexFilter.php
index 82223f08..89321b0c 100644
--- a/src/helpers/Filters/RegexFilter.php
+++ b/src/helpers/Filters/RegexFilter.php
@@ -34,6 +34,7 @@ final class RegexFilter implements Filter {
      */
     public function admits($item): bool {
         $result = @preg_match($this->regex, $item);
+        \helpers\ContentLoader::$log->debug("trying to match '{$this->regex}' against '{$item}' result: " . var_export($result));
         \assert($result !== false); // Verified at construction.
 
         return $result === 1;
```

**Comment by jtojnar** [comment]
Oh, the documentation on the website is for the master branch. I still need to decide on some way to make that clear. Ideally we would have a select box that would allow switching between versions but that is less elegant.

The version you are on only supports the filtering both title and content at the same time (described in the first point in the [filter docs](https://selfoss.aditu.de/docs/usage/filters/)).

I am not aware of any new regressions in the latest snapshot [2.20-9a3d7cf](https://cloudsmith.io/~fossar/repos/selfoss-git/packages/detail/raw/selfoss.zip/2.20-9a3d7cf/) compared to previous snapshots.

However, since the version you are using is almost a year old, and a new stable version has been released since, please read the changes in the [NEWS file](https://github.com/fossar/selfoss/compare/4fc98f6344c3771f4cf20c701ee9077cf11f6a66...9a3d7cf2d124350c235d36c149692d24918d5495#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197ea) if any of the changes affect you. Notably, if you have custom spouts or custom sharers, you will need to modify them.

**Comment by mrichtarsky** [comment]
Thanks for the helpful pointers, everything works as expected now!
