### ISSUE TITLE
some todos

### ISSUE THREAD

**Issue by caino** [fossar/selfoss#969]
1) prevent twitter feed auto load images
2) strip `<br />` between name and tweet
3) add share buttons on the right without open full article
4) mark item as favourite with a star on the left of the title
5) selected news with bold title

**Comment by jtojnar** [comment]
1. Twitter spout uses lazy loading for content images. The image you see is actually a thumbnail (implemented in #544), some RSS feeds can display them too. I was never a fan of the thumbnails, maybe we could add an option to disable them.
2. This is again intentional and was introduced in the same pull request, commit adeeb12e450d205f3f5bc8c9456507caeaa75c14. I would much prefer a single-line titles but since the titles contain the whole tweet text including line breaks, it would often overflow to the next line anyway. It would be nice if we come up with a way to show enough of the tweet in the title and move the rest to the body but it will be difficult, maybe something like @username tweeted about `#hashtag, #hashtag and keyword` but that is quickly moving to the [NLP](https://en.wikipedia.org/wiki/Natural_language_processing) realm.
3. Do you mean something like this?
![screenshot-2017-8-17 selfoss 2637](https://user-images.githubusercontent.com/705123/29415602-d8979750-8363-11e7-9721-d59e8ed19970.png) Sharing UI could definitely use some attention, though we do not want to overcrowd the rest of the interface.
4. Making the UI cluttered is definitely a concern here. Maybe we could create Custom CSS section on the wiki so users who want such changes could add it to their `user.css` file.
5. You can add `.entry.selected .entry-title {font-weight: bold;}` to your `user.css`

**Comment by caino** [comment]
1. The option to disable thumbnails would be great!
2. I've modified `item.phtml ` template adding `$title = preg_replace("/<br\W*?\/>/", " ", $title);` to remove line breaks. OMG no NLP please, it's not required xD To display much of the text in one line play with `text-overflow:ellipsis` should be enough.
3. Yeah! Exactly what I mean! There should be an option to manage this too or just use the UX pattern to display that buttons when mouse over the article ?
4. It's just sugar but it should be useful
5. Thank you for the hint!

Yes, sorry for the single issue.
Thank You very much!

**Comment by jtojnar** [comment]
1. Thumbnails can be disabled now (https://github.com/SSilence/selfoss/pull/1022)

**Comment by jtojnar** [comment]
selfoss 2.19 will place the tweet author name into the author field (introduced in https://github.com/fossar/selfoss/commit/4f4945587049a146a13cd0bc136adb0f69c77d39).
